### PR TITLE
fix: Event Date Issue Resolved

### LINKED ISSUE #186: [BUG] Logic issue in Events
### Describe the bug

Logic issues in order

image

1. Top section is today's events: date 15. ✔
2. upcoming is also containing past events dates of data ❌
3. past events: is containing only single events, should be more past events ❌

### To Reproduce

localhost: http://localhost:3000/events
website: https://www.thecyberhub.org/events

### Expected Behavior

_No response_

### Screenshot/ Video

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Ruchita-01**
## Fixes Issue

Fixes #186 

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community. 
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld). 
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by Ruchita-01** [comment]
Event Date Issue Fixed

**Review by kabir0x23 — APPROVED** [review]
Awesome 

Thanks for contributing to this project.

If you want to contribute more then must check out other open-source projects and communities:
- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

File: src/components/Events/Events.jsx [hunk 1]
```diff
@@ -39,20 +51,20 @@ const Events = () => {
             <MainEventsContainer>
                 <EventsHeading>Today's Events</EventsHeading>
```
Comment (kabir0x23) [inline src/components/Events/Events.jsx:52]: The issue number #190 is not getting resolved with.

image

because today's events are outside of the map / loop functions

so where there are no event's on today, so we want to display that heading too
